### ISSUE TITLE
WIDTH and HEIGHT in mm or px?

### ISSUE THREAD

**Issue by Samani** [openalpr/train-detector#10]
hi
I have a question.

WIDTH and HEIGHT is mm or px ?

for example :
#WIDTH=52
#HEIGHT=13
#COUNTRY='eu'

but Real HEIGHT size is 11 mm.

**Comment by matthill** [comment]
Sorry I didn't see this question until now.  Those values are in pixels.  It should roughly match the aspect ratio that all the plates have been cropped.

**Comment by Samani** [comment]
thank you.
