### ISSUE TITLE
prep.py python 3.X supports

### ISSUE THREAD

**Issue by bfelmokh** [openalpr/train-detector#34]
Hello, 

I'm facing a probem when using this training method : 

exp of error : SyntaxError: Missing parentheses in call to 'print'. Did you mean print(execStr)?

My question is : the script isn't updated to work with Python 3.X ?

Thanks.

Best Regards,

**Comment by ivanh23** [comment]
Just put spaces , it will work as it should

**Comment by theonlyNischal** [comment]
Have you tried using python2? Last time I didn't used python3 but tried with python2 and it worked.

**Comment by bfelmokh** [comment]
> Have you tried using python2? Last time I didn't used python3 but tried with python2 and it worked.

I was trying to run it with Python3. now it's Okey.

Regards,
