### ISSUE TITLE
error: (-5:Bad argument) in function 'get'

### ISSUE THREAD

**Issue by walker1001** [openalpr/train-detector#39]
I reduced the number of pos and neg images but still get this error.
Does anyone know the solution? I google it and most solutions suggest reduce neg and pos, but it didn't work.
![1](https://user-images.githubusercontent.com/46959272/91789309-99bf5b80-ec38-11ea-903d-bd8b58d16c1b.png)

**Comment by mandza** [comment]
It would be great if you post solution to this problem

**Comment by walker1001** [comment]
First of all, you should check whether you have deleted the output of the previous run or not, it actually causes my error. If it doesn't work, then you should reduce the number of positive images, specifically, the new command look like:
opencv_traincasade.......... --numPos 600 ............. 13
